config/routes.rb
Podloko::Application.routes.draw do
  root :to => "rooms#index"
  resources :rooms, :only => [:show] do
    member do
      get :claim
      get :ping
      post :update_library
      get :request_library_update
      get :play
      get :stop
    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  before_save :update_last_active
  validates_uniqueness_of :name
  
  def self.taken?(room_name)
    where(:name => room_name).count >= 1 
  end 

  def to_param
    name
  end

  def update_last_active
    self.last_active = Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  filter_parameter_logging :password
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  ### ACCESSED VIA BROWSER (HTML) ###
  # index of the site / shows available rooms
  def index
    @rooms = Room.order("updated_at DESC").limit(10)
  end

  # shows the currently available songs from a given room's ipod
  def show
    @room = Room.find_by_name(params[:id])
    @room_tracks = ActiveSupport::JSON.decode @room.tracks_json
    @room_tracks ||= []
    respond_to do |wants|
      wants.html
      wants.json { render :text => @room.to_json }
    end
  end

  def request_library_update
    @room = Room.find_by_name(params[:id])
    if @room
      Pusher[@room.name].trigger('update_library', {:message => "nil"})
    end
    flash[:notice] = "Fetching Library from iPod, check back in 10 seconds!"
    redirect_to :action => :show
  end
  
  def stop
    @room = Room.find_by_name(params[:id])
    if @room
      Pusher[@room.name].trigger('stop', [])
    end
    flash[:notice] = "Stopping iPod."
    redirect_to :action => :show
  end

  def play
    @album = params[:album]
    @track_ids = params[:track_ids] || []
    @room = Room.find_by_name(params[:id])
    if @room
      Pusher[@room.name].trigger('play', {:track_ids => @track_ids})
    end
    render :text => {"success" => true}.to_json
  end

  ### ACCESSED VIA PHONE (API) ###
  skip_before_filter :verify_authenticity_token, 
                :only => [:ping, :update_library]
  # occasionally pingback from phone, should update recently_active
  def ping
    render :text => {"success" => false}.to_json
  end
  
  def claim
    @room = Room.taken?(params[:id]) ? Room.find_by_name(params[:id]) : nil
    password_hash = nil
    message = ""
    if params.has_key?(:password)
      password_hash = Digest::SHA2.hexdigest(params[:password]) 
    end
    unless @room
      @room = Room.create(:name => params[:id], :password_hash => password_hash)
      message << "New Room Created. "
    end
    if @room.last_active < 3.hours.ago
      # stale room
      @room.update_attributes(:password_hash => password_hash)
      message << "You have reclaimed Room ##{params[:id]}. "
    end
    
    render :text => {"success" => true, "message" => message}.to_json
  end

  # POST from the phone with ipod library (query result)
  def update_library
    @room = Room.find_by_name(params[:id])
    json = ActiveSupport::Base64.decode64 params[:library]
    library_list = ActiveSupport::JSON.decode json
    
    @room.update_attribute(:tracks_json, json)
    Rails.logger.info("Room #{@room.name} ---- JSON FROM PHONE ----\n\n#{json}\n\n")
    render :text => {"success" => true}.to_json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_list_item(room)
    content_tag "li" do
      "<span class='room_id'>#{room.id}</span><span class='room_name'>#{room.name || "Unnamed" }</span><em> - last active: #{room.last_active.strftime '%H:%M %p on %A'}</em>"
    end
  end

  def playable_album_name(room, album)
    link_to "#{album["album_artist"]} - #{album["album_name"]}",
            "#{room.to_param}/play?#{album["album_name"].to_query "album"}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:regular,bold' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "reset.css" %>
  <%= stylesheet_link_tag "main.css" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "http://js.pusherapp.com/1.7/pusher.min.js" %>
  <%= yield :head_js %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="content">
    <%= yield %>
  </div>
</body>
</html>

app/views/rooms/index.html.erb
<%= content_for :title, "PodLoko - Web iPod Controller" %>
<h1>PodLoko</h1>
<ul class="rooms">
  <% @rooms.each do |room| %>
        <a href="<%= room_path(room)%>">
      <li>
        <span class="room_id"><%= room.id %></span>
        <span class="room_name"><%= room.name ||"Unnamed" %></span>
        <em> - last active: <%= room.last_active.strftime "%H:%M %p on %A" %></em>
      </li>
    </a>
  <% end %>
</ul>

app/views/rooms/show.html.erb
<% content_for :title, "#{@room.name} | PodLoko iPod Control" %>
<% content_for :head_js do %>
  <%= javascript_include_tag('tablesorter.js') %>
  <%= javascript_include_tag('jquery-ui.min.js') %>
  <%= javascript_include_tag('tablesorter_filter.js') %>
<% end %>
<%= javascript_tag :defer => 'defer' do %>
  var pusher = new Pusher('58b48fb1e1b958165a91');
  var channel = pusher.subscribe('willowtree');
  channel.bind('stop', function(data) {
  });

  var track_ids_to_query = function(track_ids) {
    var output = "";
    var count = 0;
    track_ids.each( function(index) {
      if(count > 0) {
        output += "&";
      }
      output += "track_ids[]=" + track_ids[index];
      count++;
    });
    return output;
  };

  $(document).ready(function() 
    { 
        $("#library")
          .tablesorter( {sortList: [[0,0], [1,0]]} )
          .tablesorterFilter({filterContainer: $("#library-filter-box"),
                              filterColumns: [0,1,2,3],
                              filterCaseSensitive: false});
        $( "#library-body" ).selectable({
          filter: "tr"
        });        
        $("#play-pause").click( function(){
          var selected_tracks = $("tr.ui-selected");
          var permanent_ids = selected_tracks.map( function(tr_index) {
            return selected_tracks[tr_index].children[4].innerHTML;
          })
          $.ajax({
            url: "/rooms/<%= @room.name %>/play",
            data: track_ids_to_query(permanent_ids)
          });
        });
    }
  );
<% end %>
<header class="top">
  <h1><%= @room.name %></h1>
  <h2>PodLoko</h2>
</header>

<ul class="controls">
  <%= link_to "#" do %>
    <span id="play-pause" class="play">Play</span>
  <% end %>
  <span id="skip-track" class="skip">Skip</span>
  <%= link_to request_library_update_room_path(@room) do %>
    <span id="update-lib" class="spin">Update Library</span>
  <% end %>
  <%= link_to stop_room_path(@room) do %>
    <span id="stop-all" class="stop">Stop Playback</span>
  <% end %>
  <input id="library-filter-box" placeholder="Search..."></input>
</ul>

<div class="library-container">
<table id="library" class="tablesorter">
<thead>
  <tr>
    <th class="first">Artist</th>
    <th>Album</th>
    <th>Name</th>
    <th>Time</th>
    <th class="last">Persistent ID</th>
  </tr>
</thead>
<tbody id="library-body">
  <% @room_tracks.each do |thash| %>
    <tr>
      <td><%= thash["artist"] %></td>
      <td><%= thash["album"] %></td>
      <td><%= thash["title"] %></td>
      <td><%= thash["duration"] %></td>
      <td class="last"><%= thash["persistent_id"] %></td>
    </tr>
  <% end %>
</tbody>
</table>
</div>